### ISSUE TITLE
考虑支持clickhouse吗

### ISSUE THREAD

**Issue by wangran99** [vipbooks/TableGo#3]
考虑支持clickhouse吗，大数据必用数据库

**Comment by vipbooks** [comment]
你可以手动添加扩展数据库，我手动添加了Apache Hive数据库测试没有问题，把需要的所有Jar包都放到TableGo\lib\db目录下，重要重启，db目录下的Jar包会动态加载，你把jar包放进去启动TableGo测试数据库如果报错就看下错误日志，少了什么包再往里面加，直到没有错误。可以看下使用手册，里在有说明。
你的这个Issue我很早就看到了，但是GitHub突然收不到手机验证码了，无法登录，搞了好久才搞定，有什么问题可以登录TableGo官网添加技术交流群，在群里发消息能得到及时的回复，也可以在Gitee上提Issue方便交流一些。
![1](https://github.com/user-attachments/assets/f7ac5928-1be8-4ae5-a18f-8d0a99add8e9)
![2](https://github.com/user-attachments/assets/3491c6ae-021e-4f8a-b6b4-1fc9770865be)
![3](https://github.com/user-attachments/assets/f9068e45-6ee1-4d73-b124-20a67b5f5fc0)
